# Créez vos premiers arrays avec NumPy
Cours OpenClassroom : https://openclassrooms.com/fr/courses/7771531-decouvrez-les-librairies-python-pour-la-data-science/7856832-creez-vos-premiers-arrays-avec-numpy

Découverte de Numpy

**Le But est de découvrir la difference entre un tableau python et un *array* numpy**

In [102]:
#Tableau python classique

revenus = [1800, 1500, 2200, 3000, 2172]

def moyenne(liste):
    return sum(liste)/len(liste)
moyenne(revenus) # => 2134.4 // 0.4s

2134.4

In [103]:
# Avaec Numpy maintenant

import numpy as np

np.mean(revenus) #=>2134.4 // 0.1s

2134.4

In [104]:
#Creation d'un tableau numpy
revenus_array = np.array(revenus)
revenus_array

array([1800, 1500, 2200, 3000, 2172])

In [105]:
#Connaitre le type
revenus_array.dtype 

dtype('int64')

In [106]:
#Operation numpy
revenus_array[1]

1500

In [107]:
revenus_array[1] = 2000

In [108]:
revenus_array[1]

2000

In [109]:
# revenus_arrays = array([1800, 1500, 2200, 3000, 2172])
revenus_array[1:3]

array([2000, 2200])

In [110]:
# revenus_arrays = array([1800, 1500, 2200, 3000, 2172])
revenus_array[::2]

array([1800, 2200, 2172])

On remarque que numpy marche un peu comme **Matlab**

In [111]:
revenus_array[revenus_array > 2000]

array([2200, 3000, 2172])

In [112]:
revenus_array[(revenus_array > 2000) & (revenus_array < 3000)]

array([2200, 2172])

Les methodes de numpy

In [113]:
# Connaitre les dimensions d'un tableau
revenus_array.shape

(5,)

In [114]:
#Ou mathematique
print("mean = ", revenus_array.mean())
print("max = ", revenus_array.min())
print("min = ", revenus_array.max())

mean =  2234.4
max =  1800
min =  3000


In [115]:
revenus_array = np.hstack((revenus_array, 1234))
print(revenus_array)

[1800 2000 2200 3000 2172 1234]


In [119]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [128]:
a = np.linspace(5, 10, 11)
print(a[-3:-1])
print(a[a % 2 == 0])

b = np.array([[[1, 2],[4, 5]],
            [[6, 7],[8, 9]],
            [[10, 11],[12, 13]]])
print(b)

c = b.reshape([4, 1, 3])


[9.  9.5]
[ 6.  8. 10.]
[[[ 1  2]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


In [131]:
print(b[2, :, :])

[[10 11]
 [12 13]]
